# Generated by Django 3.0.5 on 2020-04-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
    ]
